### ISSUE TITLE
Link do Git Page 

### ISSUE THREAD

**Issue by fernandoleonid** [pedrothecatholic/lampada_js#3]
Falta colocar o link do git page:
![image](https://user-images.githubusercontent.com/42476943/134052302-3e3b519b-854f-4760-924b-fd4ac163ddc3.png)

**Comment by pdroasdev** [comment]
![issue resolvida](https://user-images.githubusercontent.com/87319915/134355312-848a2e23-0517-45cd-92ea-391029e319ed.png)
